### ISSUE TITLE
Issues with table transform "table"

### ISSUE THREAD

**Issue by pavel-odintsov** [Vertamedia/clickhouse-grafana#11]
Hello!

I have a query like:
```
SELECT
    datetime,
    queryName,
    responseCode
FROM $table
WHERE
    $timeFilter
    and queryName = 'stableit.ru'
LIMIT 5
```

And I just want to get a response in table format (i.e. single column for each field).

But by default I have following format:
<img width="1280" alt="vertica_issue" src="https://user-images.githubusercontent.com/2744166/28066948-ff5b4606-6636-11e7-856d-aeb57b00030c.png">

I tried to select "Table transform: table" but it does not work and reverts to "Table transform: Time Series to rows" immediately.

Is it possible you use your awesome plugin this way? 

Plugin version: latest from Grafana.net.

**Comment by hagen1778** [comment]
Hi @pavel-odintsov 
Table format is not supported by plugin. It's a requirement of native Grafana's plugin - table. It throws error into your console if table-transform is not supported. And as i can see only Influx datasource support this feature. But still I can't use table transformation at http://play.grafana.org for Influx or any other datasource.

I am curios, which problem you want to solve? Because till now we don't have any needs in this option. Give more information about your task and I'll try to help.

**Comment by pavel-odintsov** [comment]
Thanks for help! My issue was solved. I just added date_time column and switched type to "time series to column".
