### ISSUE TITLE
help me please, create select

### ISSUE THREAD

**Issue by igor9292** [Vertamedia/clickhouse-grafana#138]
I want to make a query from a table system.proceses. I'm interested in information, the number of requests ( select count(*) from system.processes) I want to draw a graph of these changes over time, but there is no time in the table, is it possible to execute the query once a minute and draw the system time? if possible, what should the request look like?

And there is still a question, if I have several sources (clickhouse), can I somehow combine them on the graph?

**Comment by hagen1778** [comment]
Hi @igor9292 

Time column is required only for using macroses. Users are free to execute any ClickHouse queries without limits.
You can use table visualisation instead of graph for processes. You can check some query examples for plotting `system.query_log` [here](https://grafana.com/grafana/dashboards/2515)
The another option is to use histogram - see example how to do this [here](https://github.com/Vertamedia/clickhouse-grafana#vertical-histogram-httpsgrafanacompluginsgraph).
Grafana still needs time value for plotting the data, but you can fake it. See how to do this in [PieChart example](https://github.com/Vertamedia/clickhouse-grafana#working-with-panels)

> And there is still a question, if I have several sources (clickhouse), can I somehow combine them on the graph?

Yes, you can use [mixed datasource](https://grafana.com/docs/features/datasources/mixed/#mixed-data-source) feature.

**Comment by igor9292** [comment]
@hagen1778 
could write an example with the system.processes nameplate?, I can’t write such a select, i don't see graphics 

count (*)
date, when did query

**Comment by hagen1778** [comment]
Does this helps?
![image](https://user-images.githubusercontent.com/2902918/63122165-f86a5680-bf9d-11e9-86bf-08ae6615ecef.png)

**Comment by Slach** [comment]
@igor9292 thanks for reporting, I close issue, feel free open new if you have any question
