### ISSUE TITLE
[Feature Request] Support Alerting

### ISSUE THREAD

**Issue by toddyocum** [Vertamedia/clickhouse-grafana#140]
Support for alerting would be great, I see there was a Feature Request from a ling time ago that was closed.

https://github.com/Vertamedia/clickhouse-grafana/issues/3

Current backends supporting alerting. 

https://grafana.com/docs/alerting/rules/#execution

Grafana Alerting looks like a possible replacement for InfluxDB+Kapacitor.

**Comment by homekuanyi** [comment]
Could you give some examples about how to support alerting ?

**Comment by hagen1778** [comment]
Frankly speaking, it doesn't look like production ready - https://github.com/grafana/grafana-plugin-model

**Comment by toddyocum** [comment]
Ah, yeah, I didn't appreciate there was such a distinction of datasource(DS) plugins.

If Im understanding correctly, Alerting works for internal DS plugins, for a DS plugin that isn't internal, not everything is in place in Grafana to allow the plugin to support Alerting.

So either ClickHouse plugin would have to be internal, or support needs to be completed in Grafana to allow not internal plugins to be also support alerting.

**Comment by hagen1778** [comment]
Correct! External plugins are frontend-only and implemented in JS. Alerting requires some processes to run on Grafana's backend, because alerting should always work, even if user closed tab in browser. So there should be a way how to put all plugin's logic for sending requests and parsing responses on backend. So plugin authors should implement all this logic in `Go` (which is Grafana backend language), and Grafana authors find a way how to run this logic without harm to main process.

When this plugin was created few years ago, I also implemented alerting. But that's was possible only because I was running my own fork of Grafana. However, I wasn't able to keep up with Grafana's development pace so fork become outdated very fast.

**Comment by wuguanyu** [comment]
@hagen1778  If We want to support clickhouse alert by ourselves. How much cost we need ?
any difficulty ？

**Comment by hagen1778** [comment]
@wuguanyu 
Can't say, haven't looked for a year... You may want to check following code for examples:
- backend branch - https://github.com/grafana/simple-json-datasource/tree/backend-updated
- druid plugin - https://github.com/GoshPosh/druidplugin/tree/druid_alert

The parser in JS for CH responses may be found here - https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/response_parser.ts

I have no idea if current Grafana's API for backend plugins is stable, so be ready for changes in future.

**Comment by wuguanyu** [comment]
@hagen1778  Thanks a lot

**Comment by Slach** [comment]
closed by https://github.com/Vertamedia/clickhouse-grafana/pull/183
need to add dist/MANIFEST.txt and implements sign process
also need refactoring from  https://github.com/grafana/grafana-plugin-model/ to https://github.com/grafana/grafana-plugin-sdk-go
