### ISSUE TITLE
Use variable as value for database or table in Query Editor

### ISSUE THREAD

**Issue by splichy** [Vertamedia/clickhouse-grafana#141]
Hi,

It would be nice to be able to use variable as value in query editor for e.g. `database` (imagine you have multiple databases for more environments a you would like to switch dashboard to different DB by simply changing variable)
Now if I want to accomplish this I cannot simply use $table variable directly in query - as variable from Query Editor isn't evaluated.

**Example:**
$database = collectd
Query editor: database: $database table: metrics

Query: `$perSecondColumns(hwid, value) FROM $table WHERE $timeFilter AND metric IN (....`

**Result:**
`SELECT t, groupArray((hwid, max_0_Rate)) AS groupArr FROM ( SELECT t, hwid, if(runningDifference(max_0) < 0, nan, runningDifference(max_0) / runningDifference(t/1000)) AS max_0_Rate FROM ( SELECT (intDiv(toUInt32(timestamp), 900) * 900) * 1000 AS t, hwid, max(value) AS max_0 FROM `**$database**`.metrics WHERE date >= toDate(...`

**Expected result:**
`SELECT t, groupArray((hwid, max_0_Rate)) AS groupArr FROM ( SELECT t, hwid, if(runningDifference(max_0) < 0, nan, runningDifference(max_0) / runningDifference(t/1000)) AS max_0_Rate FROM ( SELECT (intDiv(toUInt32(timestamp), 900) * 900) * 1000 AS t, hwid, max(value) AS max_0 FROM collectd.metrics WHERE date >= toDate(...`

This can be workarounded with query like:
 `$perSecondColumns(hwid, value) FROM $database.metrics WHERE $timeFilter AND metric IN (....`

_But this is still workaround as  table name must be 'hardcoded' into the query._

A bit strange is that when I will fill $database into database value then I will get correct table names recommendation in table field.

**Comment by Slach** [comment]
Dear @splichy, sorry for the late response, I promise we will get more quickly and qualified feedback for our plugin users 
unfortunately, the current plugin code base can't apply `$table` macro with recursive `$templateVariable` and i don't see how we can improve it without geoengineering, feel free make PR for it


as a workaround, instead of using $table macro, you can define couple template variables in your dashboard with type Query and source <your clickhouse datasource>
`$template_db` with the following query: `SELECT name FROM system.databases`
and `$template_table` with the following query: `SELECT name FROM system.tables WHERE database IN '${template_db}'` 

and use following SQL query
```sql
SELECT
    $timeSeries as t,
    count()
FROM $template_db.$template_table
WHERE $timeFilter
GROUP BY t
ORDER BY t
```
