### ISSUE TITLE
When get DateTime from server as "YYYY-MM-DD HH:MM:SS" format, grafana interpret it as time with client timezone 

### ISSUE THREAD

**Issue by mzealey** [Vertamedia/clickhouse-grafana#318]
I'm using `$from` and `$to` everywhere in my SQL queries like `WHERE time BETWEEN toDateTime($from) AND toDateTime($to)`. Being based in UK everything is displaying correctly. However if I go into chrome dev tools and change the timezone to say US/Pacific I get an 8h truncate at the beginning of the graph (the `$from/$to` values embedded in the SQL itself change).

If I'm changing the timezone via grafana interface (display, dashboard or general setting) it makes no difference, just updates the times at the bottom of the graph (ie it continues working when in UK timezone, continues being 8h broken in US/Pacific timezone). Is there some timezone application that needs to happen within this plugin or is this more of a grafana bug?

This is grafana 7.3.4

**Comment by Slach** [comment]
I think it's an expected behavior

which time range did you use? "Last XXX hours/minutes"?
![image](https://user-images.githubusercontent.com/105560/104269592-79da5700-54b8-11eb-9ec3-e18d1fb205c9.png)

`$from` and `$to`
are macros from a clickhouse plugin, which values are always the unix timestamp and always converted from the currently selected time range in the grafana interface 

please look at the following code fragments:
https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/sql_query.ts#L119-L120

https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/sql_query.ts#L126-L127

https://github.com/Vertamedia/clickhouse-grafana/blob/master/src/sql_query.ts#L514-L521

also, Date and DateTime which income from ClickHouse server always converts to Unix Timestamp * 1000 via $timeSeries macros
on clickhouse-server side, so when you change "browser time zone" only in grafana 
you just change unix timestamp representation in graph axis-X

if you want to change values both on X and Y axis, you should change time zone in your client OS, or change time range on top-right corner in grafana interface

also, you can read details about timezones on clickhouse-side
https://clickhouse.tech/docs/en/sql-reference/data-types/datetime/

unfortunately ClickHouse HTTP interface doesn't implements "use_client_time_zone" setting now

**Comment by mzealey** [comment]
OK so digging further the issue I raised is a bit misleading. The time ranges are passed correctly.

My SQL queries are written like:

```
SELECT toStartOfInterval(time, interval $interval second) AS t, ...
```

which works fine in UTC timezone but I think the auto-conversion of those values into JS in the browser is doing the timezone calculations incorrectly.

If I change this to:

```
SELECT toUInt32(toStartOfInterval(time, interval $interval second)) * 1000 AS t
```

then it works as expected.

So it seems that somehow doing DateTime -> JS timestamp in the browser is having interference from the browser's timezone.

**Comment by Slach** [comment]
i think when you use `toStartOfInterval(time, interval $interval second) AS t`
you pass t as DateTime over JSON format without pass server timezone value, so on JS side we interpets it with browser time zone

**Comment by mzealey** [comment]
Yes we get `"2021-01-13 08:39:35"` as the timestamp value. I'm not sure why you should interpret it as browser timezone though, surely it would make more sense to interpret as UTC unless the timezone is explicitly stated? If not then I think it is important to document this bug/feature in the readme

**Comment by Slach** [comment]
I mean clickhouse doesn't pass "server time zone" over http protocol when apply FORMAT JSON for DateTime type
and grafana as HTTP clickhouse client can only format this string as JavaScript Date with browser time zone, I will investigate where conversion is happens

usually, clickhouse grafana plugin always pass time as UInt32 * 1000 inside macros

**Comment by Slach** [comment]
Unfortunatelly, we can resolve issue properly,
we can't control from plugin side how ClickHouse FORMAT JSON
