### ISSUE TITLE
Time series last point is not the real last point

### ISSUE THREAD

**Issue by aminalaee** [Vertamedia/clickhouse-grafana#36]
Hello
I've seen some weird behavior using clickhouse-grafana data source, it gets the last point from backend correctly, but it shows another value on the graph. But for other points it's showing the correct value. And this patterns is repeated for every last point.
Here are the screenshots
![rsz_screenshot_from_2018-03-04_16-51-53](https://user-images.githubusercontent.com/19784933/36946067-71ec3ece-1fcc-11e8-8ae3-4cfceb456c73.png)
![rsz_1screenshot_from_2018-03-04_16-40-00](https://user-images.githubusercontent.com/19784933/36945994-36c620a4-1fcb-11e8-8b83-67d06a173805.png)
![rsz_screenshot_from_2018-03-04_16-33-31](https://user-images.githubusercontent.com/19784933/36946003-5fe436a6-1fcb-11e8-9a52-f54275d90222.png)

**Comment by hagen1778** [comment]
Hi @aminalaee 
Plugin extrapolates last datapoint if timerange is `last N` to avoid displaying of constantly decreasing graphs when timestamp in table is rounded to minute or bigger. If it so then in 99% cases last datapoint will be much less than previous one, because last minute is not finished yet. That's why plugin checks prev datapoints and tries to predict last datapoint value just as it was already written into db. 

I understand that it's misleading a bit but u r the first who noticed this behavior. I guess, it should be configured somehow in graph settings, like `extrapolate last datapoint?`

**Comment by aminalaee** [comment]
Thank you @hagen1778 for the quick reply and this great tool. I think it'd be great if it's added to the docs somewhere and even better if it's configurable as you said. `extrapolate last datapoint` would be fine.
