### ISSUE TITLE
New [Unified Alerts] API is broken

### ISSUE THREAD

**Issue by jmpdt** [Vertamedia/clickhouse-grafana#380]
For any alert created through the Grafana 8 alerting API, I am getting this error in the Grafana server logs:

```
t=2021-11-02T10:04:33-0400 lvl=eror msg="QueryData error: unable to parse json {\"dateTimeType\":\"DATETIME\",\"extrapolate\":true,\"format\":\"time_series\",\"formattedQuery\":\"SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t\",\"hide\":false,\"intervalFactor\":1,\"intervalMs\":1000,\"maxDataPoints\":43200,\"query\":\"SELECT 1\\n\",\"rawQuery\":true,\"refId\":\"A\",\"round\":\"0s\",\"skip_comments\":true}. Error: json: cannot unmarshal bool into Go struct field Query.rawQuery of type string" logger=plugins.backend pluginId=vertamedia-clickhouse-datasource
```

My alert query is `SELECT 1`. I get the same error regardless of which table I choose as the data source. I can trigger this error message by clicking `Reformat Query` or `Run Queries`. In the `Generated SQL` dropdown, all that is displayed is `true`.

Grafana v8.2.2 and ClickHouse-Grafana v2.3.1

**Comment by Slach** [comment]
Sorry for the late reply
error message looks a little bit strange
`rawQuery` should be string even in last version of clickhouse grafana

if your query just `SELECT 1` it should not work in any grafana version

`clickhouse-grafana`  plugin expect timeseries query which contains first "t" (time) column and second column metric value or array with [category_field_value, metric_field_value]

**Comment by Slach** [comment]
@jmpdt could you check your query again and please press to "Generated SQL" in panel
it should contains SQL query

**Comment by Slach** [comment]
@jmpdt thanks a lot for reporting.
I found root reason
this is cause grafana new feature `unified alerting` use `POST /api/v1/eval` directly instead of try to process query via datasource on client-side

I need time to think how to change code editor logic to allow us to change `rawQuery` from `true` to something applicable for query processing.

**Comment by derN3rd** [comment]
> I need time to think how to change code editor logic to allow us to change `rawQuery` from `true` to something applicable for query processing.

I suggest to maybe have a similar solution as the default (my)sql datasource handles it:
- Having functions/macros (helpers, i.e. for timeframes, grouping etc) that require to put in the columns. SQL example: `$__timeGroupAlias(column,'5m') -> cast(cast(UNIX_TIMESTAMP(column)/(300) as signed)*300 as signed) AS "time"`
- When switching from Query Builder to Edit SQL he will generate the query, but you can't switch back to UI mode. Only one of them will be used at the same time
- Using one default datatype (i.e. DateTime) in querys that is expected for Grafana (others like DateTime64 or Timestamp can be casted with toDateTime64 etc)

I guess this would solve most of the client side query building, right?

**Comment by jmpdt** [comment]
@Slach thanks for looking into this!

**Comment by Slach** [comment]
@derN3rd 
thanks a lot for suggestions,
Unfortunately, we can't apply it, cause `clickhouse-grafana` plugin have different logic than MySQL
we simplify first stage interface
and on first screen we just set up the `table`, `database` and `datatime type` and `datetime` field and `date` field (not required)

And we have many client macros, which we can't be resolved on client side before pass to backend.
Cause, currently, `grafana` doesn't provide way to access `scopedVariables` when use `unified alerts` and pass data directly to `golang` backend part to `/api/v1/eval` instead of try to process it via `datasource.ts` on browser side

Only one approach will work, try to implement full compatible with `sql_query.ts` and `scanner.ts` SQL parser on golang part, but it requires a lot of work and need provide lot of tests.
