### ISSUE TITLE
disable possibility to create alert on panels with templated values

### ISSUE THREAD

**Issue by vbichov** [Vertamedia/clickhouse-grafana#392]
Currently, it is possible to create legacy alerts with templated variables even though grafana doesn't allow this.

How to reproduce: create a dashboard containing graph panel with templated value I.E:
```
SELECT
    $timeSeries as t,
    count()
FROM $table

WHERE $timeFilter
and level = ${level:singlequote}

GROUP BY t

ORDER BY t

```
go to Alert and create (and save) the alert 

notice the alert was created 

datasource version: 2.4.0
grafana version: 8.3.1

this functionality is not well documented and might mislead users

**Comment by Slach** [comment]
Unfortunately, disabling is not easy. Plugin not control "alerts" tab on frontend part
and plugin not control incoming query and not have access to last saved template variables values (this is the root reason why other Grafana's plugins doesn't provide this functionality)

Using template variables on graph panel alerts it's a side effect, vertamedia-clickhouse-datasoource plugin on backend side use `Generated SQL` (rawQuery) value as "pre-evaluted" query.

Maybe better will make PR with documentation improvements instead of disable it?

It works, and it uses template variables values which was selected during press "save" button, look to Generated SQL after change query in query editor.

**Comment by vbichov** [comment]
my guess is regular users won't dig into the docs that mutch but the docs clearly state that this is expected behavior 

https://github.com/Vertamedia/clickhouse-grafana/blob/master/README.md#alerts-support


so I'm closing the issue for now
