### ISSUE TITLE
Ad-hoc queries to dot apply with templated table name

### ISSUE THREAD

**Issue by bobrik** [Vertamedia/clickhouse-grafana#86]
We have the following query setup:

![image](https://user-images.githubusercontent.com/89186/47034323-e88aa780-d12b-11e8-9fde-1141da8dfbe1.png)

The important part here is that table is templated.

Then we also have an ad-hoc filter:

![image](https://user-images.githubusercontent.com/89186/47034434-369fab00-d12c-11e8-9b4a-2f36936850e2.png)

The filter only works if table is not specified, and it's ignored if table is specified.

My guess is that templated table name is to blame here.

**Comment by hagen1778** [comment]
Hi @bobrik 

It happened because adhoc filters comparing to the queryBuilder settings. It was a surprise for me, that variables can be used there) I also missed the fact, some people could skip query builder and adhoc filters won't work at all. In attached PR I tries to fetch database and table values from the query AST instead of queryBuilder. Please, take a look onto it.
P.S. I lack of data for testing different cases after some changes in plugin since Grafana and CH are out of my scope these days. So I am asking you to be careful and check whether other dashboards are ok with new updates. 
Thank you!

**Comment by hagen1778** [comment]
Please, see https://github.com/Vertamedia/clickhouse-grafana/releases/tag/1.8.0
