### ISSUE TITLE
Timeshift per query

### ISSUE THREAD

**Issue by volfco** [Vertamedia/clickhouse-grafana#88]
It would be extremely useful if there was a way to specify a timeshift per individual query. 

We can specify a time shift for panel, but I would like to be able to have one query that shows the current information and one that shows the previous hour, day, week, and so on.

Thanks for the great work!

**Comment by hagen1778** [comment]
Hi @volfco 

As far as I remember, `timeshift` can't be applied to separate query because we have only one graph to display all the queries. I mean, Grafana panel has only one X-axis which shows the time and if you have two queries with timeshifts it will be unclear which timerange to show on the graph. And if one of your queries is let's say `-1d` it's  results will be invisible because of `out of range` of the panel's X-axis.

**Comment by volfco** [comment]
That's a good point that I didn't think about. Seems like there shouldn't be any work needed here if Grafana could do this.

Thanks
